name: kulbal
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  google_fonts: ^6.2.1
  firebase_auth: ^5.1.0
  shared_preferences: ^2.2.3
  cloud_firestore: ^5.0.1
  google_api_availability: ^5.0.0
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo-apk.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
